.\" Manpage for vithco
.TH man 1 "26 Jun 2018" "vithco man page"
.SH NAME
vithco \- Video thumb collage creator
.SH SYNOPSIS
vithco [INPUT]
.SH DESCRIPTION
Creates a collage with 12 thumbnails extracted from the video file using ffmpeg and ImageMagick's montage
.SH OPTIONS
vithco does not take any options.
.SH SEE ALSO
FFMPEG(1), FFPROBE(1), montage(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Guilherme Henrique Nagatomo (github.com/guilhermehn/vithco)